---
title: "2019 厚數據與意義探勘工作(康老師作業)"
author: "陳聖勳"
date: "2019.8.17"
output: html_document
---

> ### 1. 在一個資料分析專案中,你認為哪個步驟會花最多的時間,為什麼?

- 我認為**資料清理**是最花時間的。
- 在大部分現實世界感測器蒐集的資料，是多元而繁雜的。而為了更精確的將雜訊資料處理掉，需要分析自己主題的需要，且非常有可能需要修正自己研究的方向，因為蒐集來的資料很有可能和你預期的不太一樣，所以就需要再做調整以及討論是否符合專案，所以我認為在此階段會花費大量時間去反覆審視自己蒐集來的資料。

> ### 2. 從程式設計(Computer Programming)到機器學習(Machine Learning),是否可以認為是種典範轉移(paradigm shift)? 為什麼?

- 否，**我個人認為程式設計和機器學習是在本質上其實是一樣的**，並無典範轉移。
- 機器學習其實也只是較程式設計更為複雜的Program，而原始的程式設計的馮紐曼模型並無實質上的改變，一樣是由input、program、output所組成，只是將input換成output的資料，進而由電腦運算出program出來，所以我認為這只是一種程式設計變成更大規模的延伸而已。

> ### 3. 數據的特徵工程(Feature Engineering) 目的為何?

- 特徵工程由在資訊處理中將原始資料轉成訓練資料的一個過程，這個方式非常重要，就是為了能更加分析數據的準確度，**避免演算法或模型因資料過於雜亂而影響到分析結果的易讀性或準確性**。

> ### 4. 請舉例說明需要”可解釋的 AI 模型”的情境

- **在需要法規規範或需要控制AI模型，或在介紹給普羅大眾和非專業者時**，不能因為準確性就選擇不可解釋的AI模型，因為在結果可能需要能看出目標客群，所以在設定AI模型時就需要讓結果產生可解釋性的結果，且可從模型建構中，了解是如何分析的方式。

> ### 5. 對你來說,模型 (model) 是什麼? 如何定義模型的好壞?

- **多層的演算法**。
- **符合預期的需求**，不管有可能是可解釋或不可解釋的模型，但能依造當時需求有可能是分析出精確的結果，或是統整出內容相關的分析，只要能在符合需求的情境出現準確率高的結果，就能算是好的模型，但如果壞模型可能可以解釋但因準確率過低或可能準確率高但不可解釋在需求的情形無法使用，就是壞模型。

> ### 6. 現今所謂的 AI 應用是否為大眾所認知的 AI? 如果不是,有哪些問題還沒解決?

- **不是**，現在的AI應用還尚未成為大眾所認知的AI。
- 在現代的AI無法輕易的依造情境變化去改變寫好的功能，且無法將自身分析出的資料和目前現況做結合，只能在設定中的資料來改善準確率，並不是人性化的去改變功能，需要人為再去改變它的程式，才有可能更符合需求。

> ### 7. 商業智慧(Business Intelligence)與整合分析(Unified Analytics) 兩者是否不同?

- **整合分析是商業智慧中處理資料的延伸。**
- 在商業智慧中主要是運用資料庫使用資料倉儲(DataWarehouse)，而目前的資料量較為龐大，傳統資料庫架構成本可能會過高，且直接使用不易。而在整合分析中是將預處理資料以DataLake的模式處理，可以更快且依造需求的使用資料的需求改變，並減少資料分析師資料處理的時間。

> ### 8. 建立我們的 data analytics team 需要注意哪些事項? 你的角色比較可能會是什麼?

- 在了解資料分析團隊需要有許多腳色，需要有了解商業問題的人、決定分析途徑的人、蒐集資料、處理資料並了解資料的人、工程師製作模型的人、使用設計模型和分析資料、評量模型的人和最重要的做決策的人。
- 我的角色可能會是工程師，將資料用圖表視覺化，並把RawData處理成可以使用的資料，我對這方面較為興趣，可以使用程式讓資料成為大家都能了解的且能拿來溝通的工具，進而讓主管做出正確的決策。
